# Generated by Django 4.0.5 on 2022-08-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.TextField(blank=True, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True, unique=True)),
                ('date', models.DateField(blank=True, null=True, unique=True)),
                ('author_1', models.TextField(blank=True, null=True, unique=True)),
                ('author_2', models.TextField(blank=True, null=True, unique=True)),
                ('author_3', models.TextField(blank=True, null=True, unique=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('image_alt', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
